### ISSUE TITLE
Договориться о том, как будет выглядеть интерфейс для Кассира и для Администратора

### ISSUE THREAD

**Issue by dimakolyandra** [dimakolyandra/kp-oop#1]
Нужно определиться, как должен выглядеть интерфейс для системы с учетом того, что мы сможем сделать. Желательно найти картинки для наглядности с тем, что мы хотим получить.

**Comment by UgolUgol** [comment]
[макеты.zip](https://github.com/dimakolyandra/kp-oop/files/4022008/default.zip)

Интерфейс для кассира

**Comment by dimakolyandra** [comment]
Done
